======================
 espectros-microzonas
======================

Aplicación web que permite obtener valores de aceleración dados una
microzona y un valor de período estructural (principalmente)

Instalación
===========

::

    $ git clone https://github.com/funvisis/espectros-microzonas.git
    $ cd espectros-microzonas
    $ virtualenv --distribute entorno
    $ source entorno/bin/activate
    $ pip install -r requirements.pip

El hecho de colocar el entorno virtual en la misma carpeta del
proyecto es una preferencia personal, así como su nombre. Así que no
es una obligación. Sí es conveniente colocar esta carpeta dentro de la
lista del ``.gitignore``.

Prueba
======

Luego de instalar el proyecto, hay que tener siempre en cuenta que
debe usarse con el entorno virtual que se creó para el proyecto. Así
que para correr el proyecto, primero se debe activar el entorno::

    $ cd <espectros-microzonas> # Supongamos la ruta completa
    $ source entorno/bin/activate
    
La configuración del proyecto debe hacerse en la carpeta
``<espectros-microzonas>/python/espectros-microzonas/conf/local/settings.py``.
Ahí simplemente asignan las opciones de configuración que sean nuevas
o diferentes a las que están en el archivo
``<espectros-microzonas>/python/espectros-microzonas/settings.py``.

A continuación, se inicializa la base de datos::

    $ cd python
    $ ./manage.py syncdb

Y por útlimo se puede poner en ejecución el servidor de pruebas para
revisar el proyecto::

    $ ./manage.py runserver

Con esto, visitando la página ``http://localhost:8000`` se puede
apreciar el proyecto desde el punto de vista del usuario.

Pre-requisitos
===============

Debe existir una instancia de GeoServer corriendo en un servidor. Para
identificar esta instancia, deben establecerse dos valores de configuración:

* GEOSERVER_URL que representa la URL con la que el proyecto Django identifica
  a la instancia de GeoServer.
* GEOSERVER_URL_CLIENT que representa la URL con la que el código cliente (JS)
  identifica a la instancia de GeoServer (es necesario porque puede que sean
  URLs diferentes a pesar de referirse al mismo servidor).

Adicionalmente, debe establecerse el valor de la configuración
``settings.GEOSERVER_MICROZONE_LAYERS`` como una lista de tuplas de tres cadenas.
Cada tupla representa una capa de microzonas y se compone de una primera cadena
que simplemente le da un nombre amigable al usuario, la segunda cadena es el
nombre formal de la capa tal cual está establecida en GeoServer y la tercera
cadena es el nombre del *atributo interesante* de la capa.

Ejemplo::

    GEOSERVER_URL = "http://localhost:8080/geoserver/Micronozas/wms"
    GEOSERVER_URL_CLIENT = "http://localhost:8080/geoserver/Micronozas/wms"
    GEOSERVER_MICROZONE_LAYERS = [('Laderas', 'Microzonas:Microzonas_Laderas', 'Amenaza'),
                              ('Sedimentos', 'Microzonas:Microzonas_Sedimentos', 'microzona'),
                              ('Amenaza General', 'Microzonas:Microzonas_Amenaza_General', 'Microzonas'),]

El *atributo interesante* es aquel que tiene como valor el nombre de la microzona
tal cual aparece en la base de datos de atributos.
